name: project_k
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  http: ^1.4.0
  either_dart: ^1.0.0
  connectivity_plus: ^6.1.4
  path_provider: ^2.1.5
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  go_router: ^16.0.0
  image_picker: ^1.1.2
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  sembast: ^3.8.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/     # 👈 Make sure to include a trailing slash


  